sequenceDiagram 

loop LifeCycle
    alt node is not the leader
        # Get healthy leader
        AppNode ->> ConsulServiceRegister : getHealthyLeader()
        ConsulServiceRegister ->> Consul : /v1/catalog/node-services/...Meta.nodeType==Master
        Consul -->> ConsulServiceRegister : Node[]
        ConsulServiceRegister ->> Consul : /v1/agent/health/service/name/[master_node_name]
        Consul -->> ConsulServiceRegister : Node[]
        ConsulServiceRegister -->> AppNode : Node {type:Leader}

        # The leader is dead
        Note right of ConsulServiceRegister : If the Node is null, the leader is dead.
        alt leader is dead
            AppNode ->> ElectionHandler : start()
            ElectionHandler ->> ConsulServiceRegister : getAllHealthyNodes()
            ConsulServiceRegister ->> Consul : /v1/catalog/node-services/...filter={}
            Consul -->> ConsulServiceRegister : Node[]
            loop check health
                ConsulServiceRegister ->> Consul : /v1/agent/health/service/name/[node_name]
                Consul -->> ConsulServiceRegister : Node[]
            end
            ConsulServiceRegister -->> ElectionHandler : Node[]
            loop for all other nodes
                ElectionHandler ->> RemoteAppNode : callAPI(node_address/vote)
                RemoteAppNode ->> RemoteAppNode : handleRequestVote()
                RemoteAppNode -->> ElectionHandler : Younger | Older
            end
            alt all other nodes say Younger
                ElectionHandler ->> ElectionHandler : onLeaderElected.Invoke
                Note right of ElectionHandler : LeaderElected event invoked
            end
            ElectionHandler -->> AppNode : void
        end
    end
end