sequenceDiagram 
    proposerNode->>proposerNode: checkNumber()
    proposerNode->>ServiceRegister: getAcceptor()
    ServiceRegister->>Consul: service?meta=acceptor:true
    Consul-->>ServiceRegister: [acceptor]
    ServiceRegister-->>proposerNode: [acceptor]
    proposerNode->>Acceptor: accept()
    Acceptor-->>proposerNode: ACK
    Acceptor->>Acceptor: validateProposerClaim()
    Acceptor->>Learner: learn()
    Learner-->Acceptor: ACK