sequenceDiagram 
    loop Unitl DistributedSystem is stable 
        Node->>ServiceRegister: getAllNodes()
        ServiceRegister->>Consul: service?meta=node:true
        Consul-->>ServiceRegister: [nodes]
        ServiceRegister-->>Node: [nodes]
        Node->>Node: assessDistributedSystem(M:1,A:2,L:1,P:n)
        Node->>Node: distributeWorkLoad()
        loop Assign Role for each node
            Node->>otherNode: role
            otherNode-->>Node: ACK
        end 
    end